TARGET = swap selection bubble qsort pointerConcept endian pointer2 functionPointer voidPointer arrayPointer

all : ${TARGET}

swap : $@
selection : $@
bubble : $@
qsort : $@
pointerConcept : $@
endian : $@
pointer2 : $@
function : $@
functionPointer : $@
voidPointer : $@
arrayPointer : $@



clean : 
	rm ${TARGET}