TARGET = swap selection bubble qsort pointerConcept endian pointer2 functionPointer voidPointer arrayPointer arrayassignment arrayCompare swapFunction sumArrayFunction sumMatrixFunction

all : ${TARGET}

swap : $@
selection : $@
bubble : $@
qsort : $@
pointerConcept : $@
endian : $@
pointer2 : $@
function : $@
functionPointer : $@
voidPointer : $@
arrayPointer : $@
arrayassignment : $@
arrayCompare : $@
swapFunction : $@
sumArrayFunction : $@
sumMatrixFunction : $@

clean : 
	rm ${TARGET}