TARGET = infinit limit celsius2fahr fahr2celsius charNumber triangle triangle2 artihmetics increment literal genderRatio compare sizeof oddeven fourBit fourBit2

all : ${TARGET}

infinit : $@
limit : $@
celsius2fahr : $@
fahr2celus : $@
charNumber : $@
triangle : $@
triangle2 : $@
artihmetics : $@
increment : $@
literal : $@
genderRatio : $@
compare : $@
compare2 : $@
sizeof : $@
oddeven : $@
fourBit : $@
fourBit2 : $@

clean : 
	rm ${TARGET}
