TARGET = absolute leafYear  posZeroNeg posZeroNeg2 bigLetter passFail grade grade2 one2Ten one2tensum multiply ascii star one2TenWhile one2TenDoWhile randomTwoint staticLocalVariable functionSum returnValue power dice sumArray sumMatrix findMax findValueArray scoreGrade baseball

all : ${TARGET}

absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
posZeroNeg2 : $@
bigLetter : $@
one2Ten : $@
one2tensum : $@
multiply : $@
ascii : $@
star : $@
one2TenWhile : $@
one2TenDoWhile : $@
randomTwoint : $@
staticLocalVariable : $@
functionSum : $@
returnValue : $@
power : $@
dice : $@
sumArray : $@
sumMatrix : $@
findMax : $@
findValueArray : $@
scoreGrade : $@
baseball : $@

clean : 
	rm ${TARGET}