TARGET = absolute leafYear  posZeroNeg posZeroNeg2 bigLetter passFail grade grade2 one2Ten one2tensum multiply ascii star
all : ${TARGET}

absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
posZeroNeg2 : $@
bigLetter : $@
one2Ten : $@
one2tensum : $@
multiply : $@
ascii : $@
star : $@

clean : 
	rm ${TARGET}